import csv
import io
import logging
import urllib.request

logger = logging.getLogger(__name__)

NIFTY500_CONSTITUENTS_URL = "https://www.niftyindices.com/IndexConstituent/ind_nifty500list.csv"

NIFTY_STOCKS = [
    "360ONE.NS", "3MINDIA.NS", "ABB.NS", "ACC.NS", "AIAENG.NS", "APLAPOLLO.NS", "AUBANK.NS", "AARTIIND.NS", 
    "AAVAS.NS", "ABBOTINDIA.NS", "ADANIENSOL.NS", "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIPOWER.NS", 
    "ATGL.NS", "AWL.NS", "ABCAPITAL.NS", "ABFRL.NS", "AEGISCHEM.NS", "AETHER.NS", "AFFLE.NS", "AJANTPHARM.NS", 
    "ALEMBICLTD.NS", "APLLTD.NS", "ALKEM.NS", "ALKYLAMINE.NS", "ALLCARGO.NS", "ALOKINDS.NS", "AMAREJABAT.NS", 
    "AMBER.NS", "AMBUJACEM.NS", "ANANDRATHI.NS", "ANGELONE.NS", "ANURAS.NS", "APARINDS.NS", "APOLLOHOSP.NS", 
    "APOLLOTYRE.NS", "APTUS.NS", "ARVINDFASN.NS", "ASAHIINDIA.NS", "ASHOKLEY.NS", "ASIANPAINT.NS", "ASTERDM.NS", 
    "ASTRAL.NS", "ATUL.NS", "AUROPHARMA.NS", "AVANTIFEED.NS", "DMART.NS", "AXISBANK.NS", "BEML.NS", "BLS.NS", 
    "BSE.NS", "BAJAJ-AUTO.NS", "BAJAJFINSV.NS", "BAJFINANCE.NS", "BAJAJHLDNG.NS", "BALAMINES.NS", "BALKRISIND.NS", 
    "BALRAMCHIN.NS", "BANDHANBNK.NS", "BANKBARODA.NS", "BANKINDIA.NS", "MAHABANK.NS", "BATAINDIA.NS", "BAYERCROP.NS", 
    "BERGEPAINT.NS", "BDL.NS", "BEL.NS", "BHARATFORG.NS", "BHEL.NS", "BPCL.NS", "BHARTIARTL.NS", "BIOCON.NS", 
    "BOSCHLTD.NS", "BRIGADE.NS", "BRITANNIA.NS", "MAPMYINDIA.NS", "CCL.NS", "CESC.NS", "CGPOWER.NS", "CIEINDIA.NS", 
    "CRISIL.NS", "CSBBANK.NS", "CAMPUS.NS", "CANFINHOME.NS", "CANBK.NS", "CGCL.NS", "CARBORUNIV.NS", "CASTROLIND.NS", 
    "CEATLTD.NS", "CENTRALBK.NS", "CDSL.NS", "CENTURYPLY.NS", "CENTURYTEX.NS", "CERA.NS", "CHALET.NS", "CHAMBLFERT.NS", 
    "CHEMPLASTS.NS", "CHENNPETRO.NS", "CHOLAHLDNG.NS", "CHOLAFIN.NS", "CIPLA.NS", "CUB.NS", "CLEAN.NS", "COALINDIA.NS", 
    "COCHINSHIP.NS", "COFORGE.NS", "COLPAL.NS", "CAMS.NS", "CONCOR.NS", "COROMANDEL.NS", "CRAFTSMAN.NS", "CREDITACC.NS", 
    "CROMPTON.NS", "CUMMINSIND.NS", "CYIENT.NS", "DCBBANK.NS", "DPABOILERS.NS", "DALBHARAT.NS", "DATAPATTNS.NS", 
    "DEEPAKNTR.NS", "DELHIVERY.NS", "DEVYANI.NS", "DIVISLAB.NS", "DIXON.NS", "LALPATHLAB.NS", "DRREDDY.NS", "EIDPARRY.NS", 
    "EIHOTEL.NS", "EPL.NS", "EASEMYTRIP.NS", "EDELWEISS.NS", "EICHERMOT.NS", "ELGIEQUIP.NS", "EMAMILTD.NS", "ENDURANCE.NS", 
    "ENGINERSIN.NS", "ENIL.NS", "EQUITASBNK.NS", "ERIS.NS", "ESCORTS.NS", "EXIDEIND.NS", "FDC.NS", "NYKAA.NS", 
    "FEDERALBNK.NS", "FACT.NS", "FINEORG.NS", "FINCABLES.NS", "FINPIPE.NS", "FSL.NS", "FIVESTAR.NS", "FORTIS.NS", 
    "GRINFRA.NS", "GAIL.NS", "GMMPFAUDLR.NS", "GMRINFRA.NS", "GALAXYSURF.NS", "GARFIBRES.NS", "GICRE.NS", "GILLETTE.NS", 
    "GLAND.NS", "GLAXO.NS", "GLENMARK.NS", "MEDPLUS.NS", "GOCOLORS.NS", "GODFRYPHLP.NS", "GODREJAGRO.NS", "GODREJCP.NS", 
    "GODREJIND.NS", "GODREJPROP.NS", "GRANULES.NS", "GRAPHITE.NS", "GRASIM.NS", "GESHIP.NS", "GRINDWELL.NS", "GUJGASLTD.NS", 
    "GNFC.NS", "GSFC.NS", "GSPL.NS", "HEG.NS", "HCLTECH.NS", "HDFCAMC.NS", "HDFCBANK.NS", "HDFCLIFE.NS", "HFCL.NS", 
    "HAPPSTMNDS.NS", "HATHWAY.NS", "HATSUN.NS", "HAVELLS.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "HINDCOPPER.NS", 
    "HINDPETRO.NS", "HINDUNILVR.NS", "HINDZINC.NS", "HONAUT.NS", "HUDCO.NS", "ICICIBANK.NS", "ICICIGI.NS", "ICICIPRULI.NS", 
    "ISEC.NS", "IDBI.NS", "IDFCFIRSTB.NS", "IDFC.NS", "IIFL.NS", "IRB.NS", "IRCON.NS", "ITC.NS", "ITI.NS", "INDIACEM.NS", 
    "IBULHSGFIN.NS", "IBREALEST.NS", "INDIAMART.NS", "INDIANB.NS", "IEX.NS", "INDHOTEL.NS", "IOC.NS", "IOB.NS", "IRCTC.NS", 
    "IRFC.NS", "INDIGOPNTS.NS", "IGL.NS", "INDUSTOWER.NS", "INDUSINDBK.NS", "NAUKRI.NS", "INFY.NS", "INOXINDIA.NS", 
    "INTELLECT.NS", "INDIGO.NS", "IPCALAB.NS", "JBCHEPHARM.NS", "JKCEMENT.NS", "JKLAKSHMI.NS", "JKPAPER.NS", "JMFINANCIL.NS", 
    "JSWENERGY.NS", "JSWSTEEL.NS", "JAMNAAUTO.NS", "J&KBANK.NS", "JINDALSTEL.NS", "JINDALSAW.NS", "JSL.NS", "JIOFIN.NS", 
    "JUBLFOOD.NS", "JUBLINGREA.NS", "JUBLPHARMA.NS", "JWL.NS", "KPRMILL.NS", "KEI.NS", "KNRCON.NS", "KPITTECH.NS", 
    "KRBL.NS", "KSB.NS", "KAJARIACER.NS", "KPIL.NS", "KALYANKJIL.NS", "KANSAINER.NS", "KARURVYSYA.NS", "KAYNES.NS", 
    "KEC.NS", "KFINTECH.NS", "KOTAKBANK.NS", "KIMS.NS", "L&TFH.NS", "LTTS.NS", "LICHSGFIN.NS", "LTIM.NS", "LT.NS", 
    "LATENTVIEW.NS", "LAURUSLABS.NS", "LXCHEM.NS", "LEMONTREE.NS", "LICI.NS", "LINDEINDIA.NS", "LUPIN.NS", "MMTC.NS", 
    "MRF.NS", "MTARTECH.NS", "MACPOWER.NS", "LODHA.NS", "MGL.NS", "M&MFIN.NS", "M&M.NS", "MAHSEAMLES.NS", "MAINDREAL.NS", 
    "MANAPPURAM.NS", "MARICO.NS", "MARUTI.NS", "MASTEK.NS", "MFSL.NS", "MAXHEALTH.NS", "MAZDOCK.NS", "MEDANTA.NS", 
    "METROBRAND.NS", "METROPOLIS.NS", "MINDACORP.NS", "UNOINDA.NS", "MSUMI.NS", "MOTILALOFS.NS", "MPHASIS.NS", "MCX.NS", 
    "MUTHOOTFIN.NS", "NATCOPHARM.NS", "NBCC.NS", "NCC.NS", "NHPC.NS", "NLCINDIA.NS", "NMDC.NS", "NOCIL.NS", "NTPC.NS", 
    "NH.NS", "NATIONALUM.NS", "NAVINFLUOR.NS", "NAZARA.NS", "NESTLEIND.NS", "NETWORK18.NS", "NIPPONLIFE.NS", "NUVAM.NS", 
    "OBEROIRLTY.NS", "ONGC.NS", "OIL.NS", "OLECTRA.NS", "PAYTM.NS", "OFSS.NS", "ORIENTELEC.NS", "PBFINTECH.NS", "PCBL.NS", 
    "PIIND.NS", "PNBHOUSING.NS", "PNCINFRA.NS", "PVRINOX.NS", "PAGEIND.NS", "PATANJALI.NS", "PERSISTENT.NS", "PETRONET.NS", 
    "PFIZER.NS", "PHOENIXLTD.NS", "PIDILITIND.NS", "PEL.NS", "PPLPHARMA.NS", "POLYMED.NS", "POLYCAB.NS", "POONAWALLA.NS", 
    "PFC.NS", "POWERGRID.NS", "PRAJIND.NS", "PRESTIGE.NS", "PRINCEPIPE.NS", "PRSMJOHNSN.NS", "PRIVISCL.NS", "PROCTER.NS", 
    "PGHL.NS", "PGHH.NS", "PNB.NS", "QUESS.NS", "RRKABEL.NS", "RBLBANK.NS", "RECLTD.NS", "RHIM.NS", "RITES.NS", "RADICO.NS", 
    "RVNL.NS", "RAILTEL.NS", "RAIN.NS", "RAJESHEXPO.NS", "RAMCOCEM.NS", "RATNAMANI.NS", "RTNINDIA.NS", "RAYMOND.NS", 
    "REDINGTON.NS", "RELAXO.NS", "RELIANCE.NS", "ROUTE.NS", "SBICARD.NS", "SBILIFE.NS", "SJVN.NS", "SKFINDIA.NS", "SRF.NS", 
    "SAFARI.NS", "SAMHI.NS", "MOTHERSON.NS", "SANOFI.NS", "SAPPHIRE.NS", "SAREGAMA.NS", "SCHAEFFLER.NS", "CIGNITITEC.NS", 
    "SHYAMMETL.NS", "SEQUENT.NS", "SFL.NS", "SHILPAMED.NS", "SCI.NS", "SHREECEM.NS", "SHRIRAMFIN.NS", "SIEMENS.NS", 
    "SIGNATURE.NS", "SINDHUTRAD.NS", "SOBHA.NS", "SOLARINDS.NS", "SONACOMS.NS", "SONATSOFTW.NS", "STARHEALTH.NS", "SBIN.NS", 
    "SAIL.NS", "SWSOLAR.NS", "STLTECH.NS", "STAR.NS", "SUDARSCHEM.NS", "SUMICHEM.NS", "SPARC.NS", "SUNPHARMA.NS", "SUNTV.NS", 
    "SUNDARMFIN.NS", "SUNDRMFAST.NS", "SUNTECK.NS", "SUPREMEIND.NS", "SUVENPHAR.NS", "SUZLON.NS", "SWANENERGY.NS", 
    "SYMPHONY.NS", "SYNGENE.NS", "SYRMA.NS", "TBZ.NS", "TCNSBRANDS.NS", "TCIEXP.NS", "TCPLPACK.NS", "TCS.NS", "TEJASNET.NS", 
    "TECHM.NS", "NIACL.NS", "RAMAKRISHNA.NS", "THERMAX.NS", "TIRUMALCHM.NS", "TITAN.NS", "TORNTPHARM.NS", "TORNTPOWER.NS", 
    "TRENT.NS", "TRIDENT.NS", "TRIVENI.NS", "TRITURBINE.NS", "TIINDIA.NS", "UCOBANK.NS", "UNOMINDA.NS", "UPL.NS", 
    "UTIAMC.NS", "UJJIVANSFB.NS", "ULTRACEMCO.NS", "UNIONBANK.NS", "UBL.NS", "MCDOWELL-N.NS", "VGUARD.NS", "VMART.NS", 
    "VIPIND.NS", "VAIBHAVGBL.NS", "VAKRANGEE.NS", "VALIANTORG.NS", "VTL.NS", "VARROC.NS", "VBL.NS", "VEDL.NS", "VENKEYS.NS", 
    "VESUVIUS.NS", "VIJAYA.NS", "VINATIORG.NS", "IDEA.NS", "VOLTAS.NS", "WELCORP.NS", "WELENT.NS", "WELSPUNIND.NS", 
    "WESTLIFE.NS", "WHIRLPOOL.NS", "WIPRO.NS", "WOCKPHARMA.NS", "YESBANK.NS", "ZFCVINDIA.NS", "ZEEL.NS", "ZENSARTECH.NS", 
    "ZOMATO.NS", "ZYDUSLIFE.NS", "ZYDUSWELL.NS"
]

_cached_nifty500: list[str] | None = None

def resolve_watchlist(configured_watchlist: list[str]) -> list[str]:
    """Resolve WATCHLIST=NIFTY500 to the current Nifty 500 Yahoo tickers."""
    if (
        len(configured_watchlist) == 1
        and configured_watchlist[0].upper() in {"NIFTY500", "NIFTY_500", "ALL"}
    ):
        return load_nifty500_watchlist()
    return configured_watchlist

def load_nifty500_watchlist() -> list[str]:
    """
    Fetch current Nifty 500 constituents from Nifty Indices.
    Falls back to the bundled list if the public CSV is temporarily unavailable.
    """
    global _cached_nifty500
    if _cached_nifty500:
        return _cached_nifty500

    try:
        request = urllib.request.Request(
            NIFTY500_CONSTITUENTS_URL,
            headers={"User-Agent": "Mozilla/5.0"},
        )
        with urllib.request.urlopen(request, timeout=10) as response:
            csv_text = response.read().decode("utf-8-sig")

        reader = csv.DictReader(io.StringIO(csv_text))
        symbols = []
        for row in reader:
            symbol = (row.get("Symbol") or "").strip()
            if symbol:
                symbols.append(f"{symbol.replace(' ', '')}.NS")

        if symbols:
            _cached_nifty500 = symbols
            logger.info(f"Loaded {len(symbols)} Nifty 500 symbols from Nifty Indices.")
            return symbols
    except Exception as e:
        logger.warning(f"Could not load Nifty 500 CSV, using bundled fallback: {e}")

    return NIFTY_STOCKS