NIFTY_STOCKS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "BHARTIARTL.NS", "INFY.NS", "ITC.NS", "L&T.NS", 
    "BAJFINANCE.NS", "HINDUNILVR.NS", "AXISBANK.NS", "KOTAKBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "SUNPHARMA.NS",
    "TITAN.NS", "ULTRACEMCO.NS", "NTPC.NS", "TATASTEEL.NS", "M&M.NS", "POWERGRID.NS", "ONGC.NS", "COALINDIA.NS",
    "ADANIENT.NS", "ADANIPORTS.NS", "WIPRO.NS", "HCLTECH.NS", "BAJAJFINSV.NS", "NESTLEIND.NS", "JSWSTEEL.NS",
    "GRASIM.NS", "HINDALCO.NS", "TECHM.NS", "TATAMOTORS.NS", "SBILIFE.NS", "HDFCLIFE.NS", "DIVISLAB.NS",
    "DRREDDY.NS", "CIPLA.NS", "APOLLOHOSP.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS", "HEROMOTOCO.NS", "BRITANNIA.NS",
    "TATACONSUM.NS", "UPL.NS", "INDUSINDBK.NS", "SBIN.NS", "BPCL.NS", "SHREECEM.NS", "TRENT.NS", "BEL.NS",
    "HAL.NS", "ZOMATO.NS", "JIOFIN.NS", "DMART.NS", "CHOLAFIN.NS", "PIIND.NS", "TVSMOTOR.NS", "LTIM.NS",
    "PIDILITIND.NS", "SRF.NS", "HAVELLS.NS", "ABB.NS", "SIEMENS.NS", "CUMMINSIND.NS", "VOLTAS.NS", "DIXON.NS",
    "POLYCAB.NS", "CGPOWER.NS", "BHEL.NS", "RVNL.NS", "IRFC.NS", "PFC.NS", "RECLTD.NS", "IREDA.NS",
    "NHPC.NS", "SJVN.NS", "SUZLON.NS", "TATACHEM.NS", "TATAPOWER.NS", "ADANIPOWER.NS", "ADANIGREEN.NS",
    "ATGL.NS", "AWL.NS", "NYKAA.NS", "PAYTM.NS", "DELHIVERY.NS", "PBFINTECH.NS", "POLICYBZR.NS", "MUTHOOTFIN.NS",
    "MANAPPURAM.NS", "M&MFIN.NS", "LICHSGFIN.NS", "CANBK.NS", "PNB.NS", "BANKBARODA.NS", "UNIONBANK.NS", "IOB.NS"
]
